language: elixir
elixir:
  - 1.4.2
otp_release:
  - 19.2
env:
  - MIX_ENV=test
before_script:
  # Set download location
  - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
  - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  # Download PLT from danielberkompas/travis_elixir_plts on Github
  # Store in $PLT_LOCATION
  - wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME
script:
  - mix test
  - dialyzer --no_check_plt --plt $PLT_LOCATION --no_native _build/test/lib/ex_uptimerobot/ebin

